local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>sf', builtin.find_files, {})
vim.keymap.set('n', '<leader>sg', builtin.git_files, {})
vim.keymap.set('n', '<leader>ss', builtin.grep_string, {})
vim.keymap.set('n', '<leader>sl', builtin.live_grep, {})
